# Generated by Django 5.1.7 on 2025-03-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothes",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="clothes/"),
        ),
    ]
